// Code generated by php2go. PLEASE DO NOT EDIT.
package full

import (
	"fmt"
)

func Foo() {
	a := int64(100)
	b := 1.5
	c := "Hello"
	d := true
	fmt.Print(a)
	fmt.Print(b)
	fmt.Print(c)
	fmt.Print(d)
	var e int64
	var f Var
	if a == int64(100) {
		e = int64(10)
	} else {
		e = int64(10)
	}
	fmt.Print(e)
	if a == int64(100) {
		f.Setint64(int64(10))
	} else {
		f.Setstring("10")
	}
	fmt.Print(f.String())
	f.SetElementTypeint64([]int64{int64(1), int64(2), int64(3)})
	fmt.Print(f.GetElementTypeint64())
	fmt.Print(f.GetElementTypeint64()[int64(1)])
	f.GetElementTypeint64()[int64(1)] = int64(10)
	fmt.Print(f.GetElementTypeint64())
	g := []int64{int64(1), int64(2), int64(3)}
	fmt.Print(g)
	g = append(g, int64(100))
	fmt.Print(g)
	f.SetmapWithKeystringWithValueint64(map[string]int64{"Key1": int64(1), "Key2": int64(2), "Key3": int64(3)})
	fmt.Print(f.GetmapWithKeystringWithValueint64())
	fmt.Print(f.GetmapWithKeystringWithValueint64()["Key1"])
	f.GetmapWithKeystringWithValueint64()["Key1"] = int64(5)
	fmt.Print(f.GetmapWithKeystringWithValueint64())
	i := int64(0)
	for i < int64(20) {
		fmt.Print(i)
		i++
	}
	for i = int64(0); i < int64(20); i++ {
		fmt.Print(i + int64(5))
	}
	qw := int64(1)
	fmt.Print(float64(qw) + 5.5 - 56.56*float64(int64(6))/float64(int64(56)))
}
